Update build-aosp.yml

diff --git a/.github/workflows/build-aosp.yml b/.github/workflows/build-aosp.yml
--- a/.github/workflows/build-aosp.yml
+++ b/.github/workflows/build-aosp.yml
@@ -32,7 +32,6 @@ jobs:
     - name: Fix Missing path_umount for 4.14
       run: |
         cd kernel_workspace/KernelSU-Next
-        # Заменяем несуществующую функцию на ту, что есть в 4.14
         sed -i 's/path_umount/do_umount/g' kernel/kernel_umount.c
 
     - name: Compile Kernel
@@ -62,10 +61,24 @@ jobs:
         make O=out vendor/sdmsteppe-perf_defconfig
         make O=out olddefconfig
 
-        make -j$(nproc --all) O=out ARCH=arm64 CC=clang \
+        # 1. Быстрая многопоточная сборка
+        if ! make -j$(nproc --all) O=out ARCH=arm64 CC=clang \
              LLVM=1 LLVM_IAS=1 \
              CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-             CONFIG_KSU=y CONFIG_KSU_KPROBE_HOOKS=y CONFIG_KPROBES=y CONFIG_KPROBE_EVENTS=y CONFIG_MODULES=y
+             CONFIG_KSU=y CONFIG_KSU_KPROBE_HOOKS=y CONFIG_KPROBES=y CONFIG_KPROBE_EVENTS=y CONFIG_MODULES=y; then
+             
+             echo "====================================================="
+             echo "MULTITHREADED BUILD FAILED!"
+             echo "RUNNING FAST SINGLE THREAD TO REVEAL EXACT ERROR:"
+             echo "====================================================="
+             
+             # 2. Мгновенный поиск ошибки в 1 поток
+             make -j1 O=out ARCH=arm64 CC=clang \
+                  LLVM=1 LLVM_IAS=1 \
+                  CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
+                  CONFIG_KSU=y CONFIG_KSU_KPROBE_HOOKS=y CONFIG_KPROBES=y CONFIG_KPROBE_EVENTS=y CONFIG_MODULES=y
+             exit 1
+        fi
 
     - name: Upload Kernel Artifact
       uses: actions/upload-artifact@v4
